[package]
name = "idct-game"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }