[workspace]
members = ["app", "game"]
resolver = "2"

[workspace.dependencies]
idct-game = { path = "game" }
base64 = "0.22.1"
rand = { version = "0.9.2", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"