[package]
name = "idct-app"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.32.0", features = ["persistence"] }
egui = { version = "0.32.0", features = ["persistence"] }
idct-game = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
